### ISSUE TITLE
Prefer SystemVerilog-2017 instead of 2012

### ISSUE THREAD

**Issue by hirooih** [lowRISC/style-guides#43]
I'd like to propose to prefer SystemVerilog-2017 instead of 2012.

Reasons are;

1. SystemVerilog-2017 is just a clarified version of SystemVerilog-2012.
2. Language Reference Manual (LRM) of SystemVerilog-2017 is available for download at no cost. 

***

The current description;

L181

> Prefer SystemVerilog-2012.
> 
> All RTL and tests should be developed in SystemVerilog, following the SystemVerilog-2012 standard, except for prohibited features.

As described in [this blog](http://www.verilab.com/blog/2018/02/ieee-std1800-2017-for-systemverilog-what-changed/), SystemVerilog 2017 has no new features.  The only functional change is *removal* of the operator overloading.  Other changes are clarifications.

We have a reference to SystemVerilog 2012 which costs $449.
On the other hand the SystemVerilog 2017 LRM is part of [IEEE GET Program](https://ieeexplore.ieee.org/browse/standards/get-program/page).  Readers can download it at no cost.

Preferring SystemVerilog-2017 encourage readers to access genuine clarified LRM and let them know SystemVerilog is a stable standard.

If you agree, I will propose a pull-request.

Thanks.

**Comment by sjgitty** [comment]
I'm supportive of this. Internally Google has migrated to recommending SystemVerilog-2017 as well. Anyone else have opinions here? @imphil @tjaychen @eunchan @msfschaffner @tomroberts-lowrisc @martin-lueker @sriyerg

**Comment by tomroberts-lowrisc** [comment]
SGTM

**Comment by msfschaffner** [comment]
Yes, I think that's a reasonable move.

**Comment by martin-lueker** [comment]
Thanks for the detailed description.  I think this is fine.

**Comment by sriyerg** [comment]
SGTM. I will check & confirm if our simulators are already relying on the 2017 spec. We may need to do the same for other ASIC tools as well.

**Comment by imphil** [comment]
SGTM
