### ISSUE TITLE
Dead link to deprecation comments

### ISSUE THREAD

**Issue by MarekPikula** [lowRISC/style-guides#6]
Found in `VerilogCodingStyle.md` at line 168:

> Use standard formatting for [comments](#comments), including C-like formatting for [TODO](https://google.github.io/styleguide/cppguide.html#TODO_Comments) and [deprecation](https://google.github.io/styleguide/cppguide.html#Deprecation_Comments).

Deprecation Comments don't exist any more in Google's guide.

**Comment by asb** [comment]
Thanks for the report - See #7 which attempts to fix this.
