### ISSUE TITLE
Inconsistent use of "simulation-synthesis mismatch"

### ISSUE THREAD

**Issue by rfdonnelly** [lowRISC/style-guides#68]
The RTL guidelines use various phrases, punctuation, and spacing for simulation-synthesis mismatches including:

* "simulation-synthesis mismatch"
* "synthesis-simulation mismatch"
* "simulation/synthesis mismatch"
* "simulation / synthesis mismatch"
* "synthesis mismatch"

Would be ideal if one form was chosen and used consistently throughout (e.g. "simulation-synthesis mismatch" singular, "simulation-synthesis mismatches" plural).  Optionally, create an appendix section on simulation-synthesis mismatches and make all mentions of simulation-synthesis mismatch a hyperlink to this section to help drive consistency and provide additional background.

**Comment by marnovandermaas** [comment]
I would go for "simulation/synthesis mismatch" because that is what the referenced paper calls it: https://www.lcdm-eng.com/papers/snug12_Paper_final.pdf
Would you like to open a PR to make this consistent?
